### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by zarinelu** [TheKingOfLight/Friedrich-Engels#2]
Ich probier mein erstes Issue aus

**Comment by zarinelu** [comment]
Wie erstelle ich jetzt einen pull request?

**Comment by TheKingOfLight** [comment]
hi

**Comment by zarinelu** [comment]
hi

**Comment by TheKingOfLight** [comment]
Bei mir: neben 'code' und 'issues' ist ein tab 'pukll requenst'
Da klickst du auf 'new pull request'
Dort kannst du auswählen welchen branch du auf welchen branch führen willst

**Comment by zarinelu** [comment]
Das hab ich auch schon alles gefunden, aber dann steht da "nothing to compare" und man kann nicht auf "create" klicken.
![grafik](https://user-images.githubusercontent.com/73024141/96337385-0d9db200-1087-11eb-9ad9-6d43ccdc23d1.png)
![grafik](https://user-images.githubusercontent.com/73024141/96337392-1ee6be80-1087-11eb-9971-9a4584ebbddc.png)

bzw es ist so

**Comment by TheKingOfLight** [comment]
update 2.0 ist noch dass gleiche wie main, wenn du aber "blacklist-update" auswählst?

**Comment by zarinelu** [comment]
> wenn du aber "blacklist-update" auswählst?
dasselbe

**Comment by TheKingOfLight** [comment]
Sag bitte bescheid, wenn es endlich klappt oder weiterhin nicht klappt
